# .github/workflows/docker-image.yml
name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - 'prerelease-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker tag
        id: get_tag
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/heads/prerelease-* ]]; then
            echo "tag=prerelease" >> $GITHUB_OUTPUT
          else
            echo "tag=prerelease" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/pwa_tasks:${{ steps.get_tag.outputs.tag || 'prerelease' }}