# .github/workflows/docker-image.yml
name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - 'prerelease-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker tag
        id: get_tag
        run: echo "tag=$(if [[ '${{ github.ref }}' == 'refs/heads/main' ]]; then echo 'latest'; elif [[ '${{ github.ref }}' == refs/heads/prerelease-* ]]; then echo 'prerelease'; else echo 'latest'; fi)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/pwa_tasks:${{ steps.get_tag.outputs.tag }}